### ISSUE TITLE
custom model question

### ISSUE THREAD

**Issue by jlgerber** [rust-qt/examples#2] opened 2019-12-11 23:49 UTC
Kudos on this project. I am quite happy with how simple it is to integrate rust into qt using these libraries. I have used all of the rust libraries for uis out there, and this is my favorite so far. The performance is far better than gtk. 

I do have a question about qt's model/view  Is there any affordance for dealing with inheritance? How if at all can i implement a custom model? Do I have to do this in c++?

**Comment by Riateche** [comment] 2019-12-12 07:18
There is no inheritance support yet, unfortunately. This is definitely the most important of the missing features right now.

**Comment by jlgerber** [comment] 2019-12-13 02:40
Well even in its current state, it is quite powerful. Really exciting.

One additional question: the ui_form1.rs example doesn't provide an example of accessing the runtime instantiated widgets from the ui file; is findChild working?

**Comment by Riateche** [comment] 2019-12-15 09:25
Yes, `findChild` is working. The example just was incomplete. I'll update it.

**Comment by Riateche** [comment] 2019-12-29 18:28
Closing as duplicate of https://github.com/rust-qt/ritual/issues/26.

**Closed as completed by Riateche** 2019-12-29 18:28 UTC
